### ISSUE TITLE
4주차 과제 질문 있습니다. DB 연결 실패

### ISSUE THREAD

**Issue by Just-love-myself** [CAUSWICT-EDU/BE-B#21]
AWS RDS 서비스에 만들어놓은 데이터베이스에 연결하려고 시도했습니다만, 실패하였습니다. 여러 에러들을 맞닥뜨렸는데, 뭐가 문제인지 모르겠습니다ㅠㅠ

1. org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.dialect.MySQL5Dialect] as strategy [org.hibernate.dialect.Dialect]
-> 주석처리하면 알아서 버전 설정해준다는 말을 본 것 같아 주석 처리해줬습니다.

2. 이후 뜬 에러입니다.
Hibernate: 
    drop table if exists app_users
2024-05-15T22:43:35.869+09:00  WARN 29004 --- [btrack] [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "
    drop table if exists app_users" via JDBC [No database selected]

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    drop table if exists app_users" via JDBC [No database selected]
-> 이를 어떻게 해결해야할지 모르겠습니다..!

<인텔리제이에서 DB Connection 성공한 모습>
![image](https://github.com/CAUSWICT-EDU/BE-B/assets/77233773/c1b56ee7-2577-4f71-9a25-229de323ef79)

<application.properties>
![image](https://github.com/CAUSWICT-EDU/BE-B/assets/77233773/28998914-347c-42ae-a742-e8e706a65a88)

**Comment by sinseongseop** [comment]
2번 같은 경우 저도 오류 생겼었는데 DB에 스키마(초기 데이터베이스)를 명시해 주지 않아서 생긴 오류였어요. 

DB에 연결해서 스키마 하나 새로 만들어 주고
spring.datasource.url=jdbc:mysql://[RDS 엔드포인트]:3306?[(초기)데이터베이스]useSSL=false&serverTimezone=UTC 이 형식으로 바꿔 주면 되요.

예시
![예시](https://github.com/CAUSWICT-EDU/BE-B/assets/102042310/3bc31155-847f-40f5-9b48-8e2448a79654)

**Comment by Just-love-myself** [comment]
우와 성섭님~ 덕분에 해결됐습니다ㅎㅎ 빠른 답변 감사해요!!
